import { DynamicModule, Module, type INestApplication } from '@nestjs/common';
import { RouterModule } from '@nestjs/core';
import { ServeStaticModule } from '@nestjs/serve-static';
import path from 'node:path';
import { createRequire } from 'node:module';
import { ENLACE_OPTIONS } from './constants.js';
import { EnlaceController } from './enlace.controller.js';
import type { SpecSource } from './specLoader.js';

const require = createRequire(import.meta.url);

// Resolved once at module load — Node's own module resolution against the
// installed `@get-enlace/ui` package (a real dependency, see package.json),
// not a relative path into this monorepo. Works identically whether
// `@get-enlace/ui` got here via an npm workspace symlink (local dev) or a
// real `node_modules` install.
const uiPackageJson = require.resolve('@get-enlace/ui/package.json');
const uiDist = path.join(path.dirname(uiPackageJson), 'dist');

export interface EnlaceOptions {
  /**
   * A file/URL path or an already-parsed object — the only input this needs
   * is a valid OpenAPI 3.x document, however it's produced or served.
   *
   * Can be omitted at module-definition time and set later via
   * `EnlaceModule.setSpec(app, spec)` in `main.ts` — useful when the spec
   * is generated by `@nestjs/swagger` (which needs the app instance to exist
   * before it can build the document, later than module imports are evaluated).
   */
  spec?: SpecSource;
  /**
   * Mount path for the canvas, e.g. `'canvas'` serves the UI at `/canvas`
   * and the spec at `/canvas/api/spec`. Defaults to `'enlace'`.
   *
   * Only available via `forRoot({ path })` — a plain `imports: [EnlaceModule]`
   * always mounts at `/enlace`.
   */
  path?: string;
}

/**
 * Internal module class used by `forRoot()` — keeps its DynamicModule
 * metadata isolated from EnlaceModule's own @Module() defaults so
 * controllers and providers aren't double-registered.
 * @internal
 */
@Module({})
class EnlaceConfiguredModule {}

/**
 * Mounts the Enlace canvas.  Import directly for zero-config defaults
 * (mounts at `/enlace`), or call `forRoot()` to customise the mount path:
 *
 *   // Zero-config — mounts at /enlace, use setSpec() in main.ts:
 *   @Module({ imports: [EnlaceModule] })
 *
 *   // With a static spec file:
 *   @Module({ imports: [EnlaceModule.forRoot({ spec: './openapi.json' })] })
 *
 *   // Custom mount path:
 *   @Module({ imports: [EnlaceModule.forRoot({ path: 'canvas' })] })
 *
 * This adapter's job is deliberately small — per ARCHITECTURE.md's MVP
 * model, execution runs entirely client-side in @get-enlace/ui, so there's
 * no `/api/run` or `/api/credentials` here at all. All this does is:
 *   - serve the raw OpenAPI document via EnlaceController
 *   - serve the built UI bundle via @nestjs/serve-static
 */
@Module({
  imports: [
    ServeStaticModule.forRoot({
      rootPath: uiDist,
      serveRoot: '/enlace',
      exclude: ['/enlace/api/{*splat}'],
    }),
    // Self-reference is safe here — TypeScript's legacy-decorator transform
    // evaluates the @Module() argument after the class expression is assigned,
    // so the EnlaceModule binding already exists. RouterModule just stores
    // the reference for later prefix resolution, no circular import.
    RouterModule.register([{ path: 'enlace', module: EnlaceModule }]),
  ],
  controllers: [EnlaceController],
  // useFactory (not useValue) so each NestFactory.create() gets its own
  // options object — otherwise setSpec() on one app would leak into another.
  providers: [{ provide: ENLACE_OPTIONS, useFactory: () => ({ spec: undefined }) }],
})
export class EnlaceModule {
  /**
   * Set the OpenAPI spec after the app is built — the one-liner for
   * `@nestjs/swagger` users:
   *
   *   EnlaceModule.setSpec(app, SwaggerModule.createDocument(app, config));
   *
   * Works because EnlaceController reads `options.spec` fresh on every
   * request (via `loadSpec`), not a snapshot taken at module-definition
   * time — so whatever's assigned here is what gets served.
   */
  static setSpec(app: INestApplication, spec: SpecSource): void {
    const options = app.get<EnlaceOptions>(ENLACE_OPTIONS);
    options.spec = spec;
  }

  /**
   * Optional explicit configuration — only needed when passing a static
   * spec at module-definition time or customising the mount path. For
   * `@nestjs/swagger` users, prefer the zero-config direct import +
   * `setSpec()`.
   */
  static forRoot(options?: { spec?: SpecSource; path?: string }): DynamicModule {
    const opts: EnlaceOptions = { spec: options?.spec, path: options?.path };
    const mountPath = opts.path ?? 'enlace';

    return {
      // EnlaceConfiguredModule (not EnlaceModule) so the DynamicModule
      // metadata doesn't merge with EnlaceModule's own @Module() defaults.
      module: EnlaceConfiguredModule,
      imports: [
        ServeStaticModule.forRoot({
          rootPath: uiDist,
          serveRoot: `/${mountPath}`,
          exclude: [`/${mountPath}/api/{*splat}`],
        }),
        RouterModule.register([{ path: mountPath, module: EnlaceConfiguredModule }]),
      ],
      controllers: [EnlaceController],
      providers: [{ provide: ENLACE_OPTIONS, useValue: opts }],
    };
  }
}
